### ISSUE TITLE
Verify that livescores work

### ISSUE THREAD

**Issue by jonhue** [jonhue/tip-the-world-cup#1]
I checked if my initial solution was still working by testing it against the following querys:

* https://www.google.com/search?q=France+vs+usa
* https://www.google.com/search?q=germany+vs+italy+euro+2016

Here is the output:

```
$ doc = Nokogiri::HTML(open("https://www.google.com/search?q=France+vs+usa"))
$ content = doc.css('div.VewdRc div.eb7Tab > div').first&.content
=> "1 - 1"

$ doc = Nokogiri::HTML(open("https://www.google.com/search?q=germany+vs+italy+euro+2016"))
$ content = doc.css('div.VewdRc div.eb7Tab > div').first&.content
=> "1 - 1(6 - 5)"
```

**Comment by sarahdayan** [comment]
@jonhue Sorry my brain malfunctioned for a moment. I didn’t realize you built the script against older games, and the UI will probably change in a similar fashion for bew ones as soon as we have scores 👍🏻
